#!/bin/bash

# Welcom to my To-Do-List script. Ive sectioned this script into different parts
# The parts are:

# 	- The file wehre tasks will be stored
# 	- Create the file if it doesnt exist

#	- Add a new task
#	- List all tasks
#	- Remove a specif task by number
#	- Clear all tasks
#	- Main Menu Loop

# ---------------------------------------------------------------------------------
# Step 1: Define the Storage Files and Functions

# The task will be stored in here

TODO_FILE="todo.txt"

if [[ ! -f $TODO_FILE ]]; then
	touch "$TODO_FILE"
	echo "Created the To-Do txt"
fi

# ---------------------------------------------------------------------------------
# Step 2: Add a New Task

  # Add the task into the todo.txt
  
  add_task() {
	echo "Enter a Task"
	read -r task
	echo "$task" >> "$TODO_FILE"
	echo "Task Added!"

  }

# add_task
# ---------------------------------------------------------------------------------
# Step 3: List All Task

 # Read all the task from the file and display them with numbering 

  list_task() {
	echo "Your To-Do List:"

	if [ ! -s $TODO_FILE ];  then
		echo "Task list is empty"
	else	
		 cat -n $TODO_FILE
	fi 

}

# list_task

# ---------------------------------------------------------------------------------
# Step 4: Remove a Task

 # Delete the task by the number of it
 
 delete_task() {
	echo "Enter the number of the task you would like to delete"
	

}


# ---------------------------------------------------------------------------------
# Step 5: Clear All Task

 # Clear all the tasks
 
 clear_all_task() {
 	if [ ! -s $TODO_FILE ]; then
	 	echo "Error: Cant clear the task list because it's empty"
 	else 
	 	truncate -s 0 $TODO_FILE
	 	echo "Cleared all tasks!"
 	fi
}

# clear_all_task

# ---------------------------------------------------------------------------------
# Step 6: Menu

while true; do
	echo -e "\n--- To-Do List Manager --------"
	echo "1. Add Task"
	echo "2. List Task"
	echo "3. Remove Task"
	echo "4. Clear All Task"
	echo "5. Exit"
	echo " ------------------------------"
	echo "Choose an option"

	read -r choice

	case $choice in
		1) add_task ;;
		2) list_task ;;
		3) delete_task ;;
		4) clear_all_task;;
		5) echo "Goodbye"; exit 0;;
		*) echo "Invalid Option"
	esac
done




# ---------------------------------------------------------------------------------
