#!/bin/bash

# Welcom to my To-Do-List script. Ive sectioned this script into different parts
# The parts are:

# 	- The file wehre tasks will be stored
# 	- Create the file if it doesnt exist

#	- Add a new task
#	- List all tasks
#	- Remove a specif task by number
#	- Clear all tasks
#	- Main Menu Loop

# ---------------------------------------------------------------------------------
# Step 1: Define the Storage Files and Functions

# The task will be stored in here

TODO_FILE="todo.txt"

if [[ ! -f $TODO_FILE ]]; then
	touch "$TODO_FILE"
	echo "Created the To-Do txt"
fi

# ---------------------------------------------------------------------------------
# Step 2: Add a New Task

  # Add the task into the todo.txt
  
  add_task() {
	echo "Enter a Task"
	read -r task
	echo "$task" >> "$TODO_FILE"
	echo "Task Added!"

  }

add_task
# ---------------------------------------------------------------------------------
# Step 3: List All Task

 # Read all the task from the file and display them with numbering 
 #
  list_task() {
	echo "Your To-Do List:"

	if [ ! -s $TODO_FILE ];  then
		echo "Task list is empty"
	else	
		 cat -n $TODO_FILE
	fi 

}

list_task

# ---------------------------------------------------------------------------------
# Step 4: Remove a Task
# ---------------------------------------------------------------------------------
# Step 5: Clear All Task
# ---------------------------------------------------------------------------------
# Step 6: Menu
# ---------------------------------------------------------------------------------
